name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-javascript:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runtime: [node, deno, bun]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '28'
          gleam-version: '1.14.0'

      - uses: actions/cache@v4
        with:
          path: build/packages
          key: ${{ runner.os }}-gleam-${{ hashFiles('manifest.toml') }}
          restore-keys: |
            ${{ runner.os }}-gleam-

      - uses: denoland/setup-deno@v2
        if: matrix.runtime == 'deno'
        with:
          deno-version: '^2'
      - uses: oven-sh/setup-bun@v2
        if: matrix.runtime == 'bun'
        with:
          bun-version: latest
      - run: gleam deps download
      - run: pnpm install
      - run: node ./dev/build-ffi.mjs
      - run: gleam build -t javascript

      - run: gleam test -t javascript --runtime ${{ matrix.runtime }}

  format-javascript:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - uses: actions/setup-node@v4
        if: matrix.files == 'javascript'
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: ./node_modules/.bin/oxfmt --check

  format-gleam:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '28'
          gleam-version: '1.14.0'
      - run: gleam format --check src test dev
