name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '28'
          gleam-version: '1.14.0'
          rebar3-version: '3'
          # elixir-version: "1"
      - uses: pnpm/action-setup@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: '^2'
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: gleam deps download
      - run: pnpm install
      - run: pnpm build:javascript
      - run: gleam test -t javascript --runtime node
      - run: gleam test -t javascript --runtime deno
      - run: gleam test -t javascript --runtime bun
      - run: gleam format --check src test
